version: "3"
services:
  server:
    restart: always
    image: nimmis/spigot:latest
    ports:
      - "25565:25565"
    environment:
      SPIGOT_VER: 1.18
      EULA: 'true'
      MC_MAXMEM: 2g
      MC_MINMEM: 512m
    volumes:
      - './minecraft-data:/minecraft'
